# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# defaults:
  # - hydra/launcher: submitit_slurm

seed: 0
data: world # mnist
potential_model: ${potential_model_mlp}
batch_size: 128

num_train_iter: 50000

potential_model_mlp:
  _target_: meta_ot.models.PotentialMLP
  n_hidden: 1024
  n_hidden_layer: 3


optim:
  _target_: optax.adam
  learning_rate: 1e-3

max_grad_norm: 1.

hydra:
  run:
    dir: ./exp/local/${now:%Y.%m.%d}/${data}_${now:%H%M}
  # sweep:
  #   dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${experiment}
  #   subdir: ${hydra.job.num}
  # launcher:
  #   max_num_timeout: 100000
  #   timeout_min: 4319
  #   partition: scavenge
  #   mem_gb: 64
  #   gpus_per_node: 1
