# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# defaults:
  # - hydra/launcher: submitit_slurm

seed: 0

image_1: data/paintings/601f.png
image_2: data/paintings/b486.png

batch_size: 1024
cycle_loss_weight: 3.
num_train_iter: 20001
l2_penalty: 1e-6

hydra:
  run:
    dir: ./exp/local/${now:%Y.%m.%d}/color_transfer_single_${now:%H%M}
  # sweep:
  #   dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${experiment}
  #   subdir: ${hydra.job.num}
  # launcher:
  #   max_num_timeout: 100000
  #   timeout_min: 4319
  #   partition: scavenge
  #   mem_gb: 64
  #   gpus_per_node: 1
